import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { useLocation } from "wouter";
import "/src/index.css";

const studies: Record<string, { title: string; category: string; year: string; intro: string; body: string; video: string; stats: string[] }> = {
  "graph-intelligence": { title: "Graph Intelligence", category: "INVESTIGATION SYSTEM", year: "2026", intro: "Making hidden relationships legible.", body: "Graph Intelligence turns a dense transaction graph into an investigative surface. Entities, clusters, relay paths, and address behavior resolve into a readable trail so an analyst can move from a signal to its evidence without losing context.", video: "https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4", stats: ["184,392 addresses observed", "14 connected nodes", "0.87 explainable risk"] },
  "signal-fusion": { title: "Signal Fusion", category: "RISK MODELING", year: "2026", intro: "Two signals. One accountable score.", body: "Signal Fusion combines ledger patterns with P2P traffic behavior. GraphSAGE, PageRank enrichment, and relay timing converge into a score that explains its own reasoning instead of hiding behind a black box.", video: "https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4", stats: ["0.82 graph risk", "0.91 traffic anomaly", "184ms inference"] },
};

export default function CaseStudy({ slug }: { slug?: string }) { const [, navigate] = useLocation(); const study = studies[slug || "graph-intelligence"] || studies["graph-intelligence"]; return <main className="case-study"><header className="case-header"><button onClick={() => { if (window.__sentrixNavigate) window.__sentrixNavigate("/"); else navigate("/"); }}><ArrowLeft size={15} /> BACK TO WORKS</button><span>SENTRIX / CASE STUDY</span></header><section className="case-hero"><div><span className="section-index">{study.category} / {study.year}</span><h1>{study.title}</h1><p>{study.intro}</p></div><div className="case-media"><video autoPlay muted loop playsInline preload="metadata" src={study.video} /><div className="case-media-label">MOTION STUDY / SIGNAL ACTIVE</div></div></section><section className="case-detail"><div className="case-stats">{study.stats.map((stat) => <span key={stat}>{stat}</span>)}</div><div className="case-copy"><span className="section-index">01 / THE APPROACH</span><p>{study.body}</p><button className="case-platform" onClick={() => { if (window.__sentrixNavigate) window.__sentrixNavigate("/platform"); else navigate("/platform"); }}>EXPLORE THE PLATFORM <ArrowUpRight size={16} /></button></div></section><footer className="case-footer">SENTRIX / TRANSACTION INTELLIGENCE <span>© 2026 TEAM SENTRIX</span></footer></main>; }

export { studies };
